name: Generate full-red contribution snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/snake.yml"
      - "README.md"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: diyayoon
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%23E40216&color_dots=%2364040A,%238D000D,%23AE0310,%23C90112,%23E70518
            dist/github-contribution-grid-snake-dark.svg?color_snake=%23E70518&color_dots=%2364040A,%238D000D,%23AE0310,%23C90112,%23E70518

      - name: Publish snake to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          commit_message: "Update full-red contribution snake"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
